Personal portfolio project for Microverse
Jusha25/personal-portfolio pull request #2
Opened 2022-05-28 17:00 UTC by Jusha25

Personal porfolio project
#Built in: Html, css, Linters.

This project can be cloned and run on local machine. It is mobile website version and made on second (secondpage) branch of personal portfolio project and made by using Flexbox and Grid Layout.

2022-05-28 19:14 UTC, cwaku requested changes
Hi @Jusha25, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there! Implement these changes and you'll be in a good spot to get your project approved. 💪🏾 

## Highlights
✅ Correct use of Github Flow 👍🏾 
✅ No linter errors 💯 
✅ Descriptive Pull Request 🥇 

![](https://media.giphy.com/media/oBCVnUOncBQE0ybNsG/giphy.gif)

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-28 19:14 UTC, cwaku commented on index.html
> +    </section>
- [ ] As I stated with the other requirement it's very important that is at its best. Let's follow the design template to make our work look awesome. 👍🏾 

<html>
<body>
<!--StartFragment--><p dir="auto" style="box-sizing: border-box; margin-top: 0px !important; margin-bottom: 16px; color: rgb(201, 209, 217); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Please ignore the green and orange borders around the elements</p>

Figma design | Your design
-- | --
![image](https://user-images.githubusercontent.com/29071984/170839572-5b057857-b3ba-4b6d-b57c-042f2d3a2183.png) |  ![image](https://user-images.githubusercontent.com/29071984/170839101-0f09db58-8abf-41c5-8d6f-d4be38dfa284.png)


<!--EndFragment-->
</body>
</html>

2022-05-30 20:30 UTC, mikethreels requested changes
Hi Shaili, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-30 20:30 UTC, mikethreels commented on index.html
> +        <h1 class="section-title">Tonic</h1>
- [ ] there can only by 1 'h1' tag on your page.

2022-05-30 20:30 UTC, mikethreels commented on index.html
> +        <p>
- [ ] the content of each card in the works class should be aligned with flexbox.

2022-05-30 20:30 UTC, mikethreels commented on index.html
> +            href="https://www.linkedin.com/feed/"
- [ ] the content of the about myself section should be aligned using flexbox

2022-05-31 05:47 UTC, elmar8287 approved these changes
Hi, 

# APPROVED  👍 🥇 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

Congratulations! 🎉 

![](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-31 08:20 UTC, merged

2022-05-31 08:20 UTC, Jusha25 commented
thank you very much

2022-08-17 14:13 UTC, Qoosim reviewed
# **Status: Approved** :tada: 

Hi @Jusha25 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- The Pull Request is following the GitHub Flow :heavy_check_mark: 
- The PR title and description are professional and descriptive :heavy_check_mark: 
- The commit messages are meaningful :heavy_check_mark:  
- Linters are working properly :heavy_check_mark: 

<img src="https://media3.giphy.com/media/xT0xezQGU5xCDJuCPe/giphy.gif"/>

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._